import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AuthProvider } from "@/context/AuthContext";
import { cookies } from "next/headers";
import { jwtDecode } from "jwt-decode";
import SidebarComponent from "@/components/common/SidebarComponent";
import Navbar from "@/components/common/Navbar";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const token = (await cookies()).get("token")?.value;
  let role: "admin" | "customer" | undefined;

  if (token) {
    try {
      const decoded: any = jwtDecode(token);
      role = decoded?.role;
    } catch {
      role = undefined;
    }
  }
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider intitalRole={role}>
          <SidebarProvider>
            <ToastContainer />
            <div className="flex flex-col w-full space-y-7">
             <div>
               <Navbar />
             </div>

              {children}
            </div>
          </SidebarProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
